#!/usr/bin/env python3
"""
AKP 规范化落库脚本 v2.2
支持自定义日期参数
"""
import sys
import os
from datetime import datetime


def detect_type_from_url(url):
    """根据 URL 模式推断内容类型"""
    url_lower = url.lower()
    if any(d in url_lower for d in ['youtube.com', 'youtu.be']):
        return 'youtube'
    if 'arxiv.org' in url_lower or url_lower.endswith('.pdf'):
        return 'paper'
    return 'article'


def save_markdown(url, summary, tags, content_type=None, custom_date=None):
    """保存剪报 Markdown 到 raw/{type}/ 目录"""
    # 自动检测类型
    if not content_type or content_type == 'auto':
        content_type = detect_type_from_url(url)

    # 确保 content_type 是有效值
    valid_types = ['article', 'youtube', 'paper', 'misc']
    if content_type not in valid_types:
        content_type = 'misc'

    # 构建路径 — 优先使用环境变量，否则走默认路径
    HOME = os.environ.get("HOME", os.environ.get("USERPROFILE", "/home/ubuntu"))
    WORKSPACE = os.environ.get(
        "AKP_WORKSPACE",
        os.path.join(HOME, ".openclaw/workspace/common/knowledge/AKP")
    )

    # 本地开发环境检测
    knowledge_dir = os.path.dirname(os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.abspath(__file__))
    )))
    local_path = os.path.join(knowledge_dir, "AKP")
    if os.path.exists(local_path):
        WORKSPACE = local_path

    # 路由到 raw/{type}/ 子目录
    base_dir = os.path.join(WORKSPACE, "raw", content_type)
    os.makedirs(base_dir, exist_ok=True)

    # 使用自定义日期或当前日期
    if custom_date:
        date_str = custom_date
        timestamp = custom_date.replace("-", "") + "_000000"
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        date_str = datetime.now().strftime("%Y-%m-%d")

    filename = f"Clipping_{timestamp}.md"

    md_content = f"""---
date: {date_str}
tags: [{tags}]
source: {url}
type: {content_type}
---


# 知识剪报


## 💡 核心摘要 & 论点
{summary}

---

## 📥 原始内容 (Raw Data)
> 内容通过外部工具提取，原始链接见 source 字段

---
*Generated by AKP_Link_Harvester v2.2*
"""

    results = []
    try:
        # 写入 raw/{type}/
        raw_path = os.path.join(base_dir, filename)
        with open(raw_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
        results.append(f"raw/{content_type}/{filename}")

        return f"Success: {' + '.join(results)}"
    except Exception as e:
        return f"Error saving file: {str(e)}"


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python save_to_workspace.py <url> <summary> <tags> [type] [date]")
        print("  type: article | youtube | paper | misc (default: auto-detect)")
        print("  date: YYYY-MM-DD (optional, default: today)")
        sys.exit(1)

    url = sys.argv[1]
    summary = sys.argv[2]
    tags = sys.argv[3]
    content_type = sys.argv[4] if len(sys.argv) > 4 else None
    custom_date = sys.argv[5] if len(sys.argv) > 5 else None

    result = save_markdown(url, summary, tags, content_type, custom_date)
    print(result)
