#!/usr/bin/env python3
import sys
import os
from datetime import datetime

def save_markdown(url, summary, tags):
    # 使用显式 WORKSPACE 常量构建路径，确保 Syncthing 同步
    HOME = os.environ.get("HOME", "/home/ubuntu")
    WORKSPACE = os.path.join(HOME, ".openclaw/workspace")
    
    # 存放在 common 目录下以实现多节点同步
    base_dir = os.path.join(WORKSPACE, "common/knowledge/AKP/links")
    os.makedirs(base_dir, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    date_str = datetime.now().strftime("%Y-%m-%d")
    
    filename = f"Clipping_{timestamp}.md"
    filepath = os.path.join(base_dir, filename)
    
    md_content = f"""---
date: {date_str}
tags: [{tags}]
source: {url}
---


# 知识剪报


## 核心摘要 & 论点
{summary}


---
*Generated by AKP_Link_Harvester*
"""
    
    try:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(md_content)
        return f"Success: {filepath}"
    except Exception as e:
        return f"Error saving file: {str(e)}"


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python save_to_workspace.py <url> <summary> <tags>")
        sys.exit(1)
        
    url = sys.argv[1]
    summary = sys.argv[2]
    tags = sys.argv[3]
    
    result = save_markdown(url, summary, tags)
    print(result)
